// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Prisma does not use a TypeScript config file by default.
// Configuration is typically done in schema.prisma and .env files.
// If you need to access environment variables, you can do so here.

console.log("DATABASE_URL:", process.env["DATABASE_URL"]);
